/**
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * (created by generateTranslationTypes.ts based on `app/locales/en.json`)
 *
 * Provides an override for the i18next TranslationFunction with type safety for keys and interpolation keys. 
 *
 **/

export interface Interpolations {
	"404.back": [],
	"404.description": [],
	"404.subtitle": [],
	"404.title": [],
	"app.title": [],
	"auth.account": [],
	"auth.calendar": [],
	"auth.gmail": [],
	"auth.loggedInAs": ['name'],
	"auth.login": [],
	"auth.logout": [],
	"auth.maps": [],
	"calendar.createEvent": [],
	"calendar.createEvent.description": [],
	"calendar.scheduledFor": ['date'],
	"common.apply": [],
	"common.cancel": [],
	"common.date": [],
	"common.description": [],
	"common.save": [],
	"common.submit": [],
	"common.today": [],
	"error.calendar.required": [],
	"features.calendar": [],
	"features.hotkey": [],
	"home.currentDate": ['date'],
	"X_LAST_KEY_SORT_HELPER_TRAILING_COMMA_PLACEHOLDER": [],
}

export type TypedTranslationFunction = <
  T extends keyof Interpolations
>(
  key: T,
  ...args: Interpolations[T] extends [] 
    ? [] 
    : [interpolationMap: Record<Interpolations[T][number], string>]
) => string;
