name: i18n-ai-translate

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: What changed?
  push:
    branches:
    - 'master' # only on master branch
    tags-ignore:
      - '**' # dont trigger extra runs on tag creation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: i18n-ai-translate
        uses: taahamahdi/i18n-ai-translate@master
        with:
          author-name: thavixt
          author-email: komlosi.peti@gmail.com
          json-file-path: locales/en.json
          language: en
          engine: gemini
          model: gemini-2.0-flash
          api-key: ${{ secrets.GOOGLE_AI_STUDIO_API_KEY }}
          templated-string-prefix: "{{"
          templated-string-suffix: "}}"
          # batch_size: 32